In [1]:
import numpy as np

data = {i : np.random.randn() for i in range(7)}
data

{0: 0.6998579490269878,
 1: -0.21396519597184838,
 2: -0.16269208577632494,
 3: 0.41682219639118734,
 4: 1.037857728025125,
 5: -0.5033403131908634,
 6: -0.7643981369606025}

In [2]:
print data

{0: 0.6998579490269878, 1: -0.21396519597184838, 2: -0.16269208577632494, 3: 0.41682219639118734, 4: 1.037857728025125, 5: -0.5033403131908634, 6: -0.7643981369606025}


In [5]:
def add_numbers(a, b):
    """
    Add two numbers together
    """
    return a + b;

add_numbers(1, 2)

3

In [6]:
?add_numbers

In [7]:
## Matrix Algebra

a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3], [4, 5, 6]])
print a
print b

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [9]:
a.shape = (5,1)

In [10]:
a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
a = np.random.random_integers(1, 5, size=(3, 3))
print a

[[4 5 5]
 [1 5 2]
 [4 1 2]]


In [12]:
b = np.array([[1, 2, 3], [4, 5, 6]])
np.transpose(b)
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
np.transpose(b)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
b = np.random.random_integers(1, 5, size=(3,3))
b.T
b_symm = (b + b.T)/2
print b_symm

[[2 3 3]
 [3 1 1]
 [3 1 4]]


In [15]:
a = np.random.random_integers(1, 5, size=(3,3))
b = np.random.random_integers(1, 5, size=(3,3))
a + b

array([[3, 7, 8],
       [6, 8, 9],
       [9, 4, 8]])

In [16]:
2 * a

array([[ 4,  8, 10],
       [ 8,  8,  8],
       [ 8,  2,  6]])

In [17]:
a * 2

array([[ 4,  8, 10],
       [ 8,  8,  8],
       [ 8,  2,  6]])

In [18]:
np.dot(a, b)

array([[35, 37, 51],
       [32, 40, 52],
       [21, 25, 32]])

In [19]:
np.dot(b, a)

array([[26, 19, 26],
       [40, 29, 41],
       [42, 37, 52]])

In [20]:
a

array([[2, 4, 5],
       [4, 4, 4],
       [4, 1, 3]])

In [21]:
b

array([[1, 3, 3],
       [2, 4, 5],
       [5, 3, 5]])

In [24]:
c = np.random.random_integers(1, 5, size=(3,3))
c

array([[1, 3, 3],
       [1, 1, 2],
       [2, 2, 1]])

In [25]:
np.dot(np.dot(a, b), c)

array([[174, 244, 230],
       [176, 240, 228],
       [110, 152, 145]])

In [26]:
np.dot(a, np.dot(b, c))

array([[174, 244, 230],
       [176, 240, 228],
       [110, 152, 145]])

In [27]:
# Transpose is not commutative
np.dot(a, b).T

array([[35, 32, 21],
       [37, 40, 25],
       [51, 52, 32]])

In [28]:
np.dot(b.T, a.T)

array([[35, 32, 21],
       [37, 40, 25],
       [51, 52, 32]])

In [29]:
o = np.ones((5, 1))
o

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [30]:
i = np.random.random((5, 1)) * 10
i

array([[ 8.21435893],
       [ 7.4209735 ],
       [ 8.19359605],
       [ 0.66289608],
       [ 0.21787781]])

In [32]:
x = np.column_stack((o, i))

In [33]:
np.dot(x.T, x)

array([[   5.        ,   24.70970238],
       [  24.70970238,  190.16845855]])

In [34]:
e = np.random.random((5, 1))
e
np.dot(e.T, e)

array([[ 2.24557648]])

In [35]:
np.diag(a)

array([2, 4, 3])

In [36]:
np.diag(np.diag(a))

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 3]])

In [37]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [38]:
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [43]:
np.identity((3))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [44]:
np.identity(3, dtype = np.int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [45]:
x = np.random.random_integers(1, 5, size =(2, 2))
x

array([[2, 2],
       [1, 4]])

In [46]:
np.linalg.det(x)

6.0

In [47]:
a

array([[2, 4, 5],
       [4, 4, 4],
       [4, 1, 3]])

In [48]:
np.linalg.det(a)

-28.000000000000011

In [49]:
np.linalg.det(a)

-28.000000000000011

In [50]:
np.linalg.matrix_rank(a)

3

In [52]:
a[:, [1]] * 2

array([[8],
       [8],
       [2]])

In [53]:
x = np.array([[4, 7], [2, 6]])

In [54]:
np.linalg.inv(x)

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [55]:
xi = np.linalg.inv(x)

In [56]:
np.dot(x, xi)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [57]:
x

array([[4, 7],
       [2, 6]])

In [58]:
xi

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

In [59]:
y = np.array([[2, 1], [2, 2]])
np.linalg.det(y)

2.0

In [60]:
np.linalg.inv(y)

array([[ 1. , -0.5],
       [-1. ,  1. ]])

In [62]:
# pandas series
import pandas as pd
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [63]:
obj2['a']

-5

In [64]:
obj2['d']

4

In [65]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [66]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [67]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [68]:
'b' in obj2

True

In [69]:
'e' in obj2

False

In [71]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)

In [72]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [73]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)

In [74]:
obj4

California      NaN
Ohio          35000
Oregon        16000
Texas         71000
dtype: float64

In [75]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [76]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [77]:
obj3 + obj4

California       NaN
Ohio           70000
Oregon         32000
Texas         142000
Utah             NaN
dtype: float64